name: gamevault

services:

  api-gateway:
    restart: unless-stopped
    container_name: api-gateway
    image: api-gateway:0.1
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - mongo-api
      - steam-games-api
    networks:
      - app-network

  auth-service:
    restart: unless-stopped
    container_name: auth-service
    image: auth-service:0.1
    build: ./auth-service
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/gamevault
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    networks:
      - app-network

  mongo-api:
    restart: unless-stopped
    container_name: mongo-api
    build: ./mongo-api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/gamevault
      - PORT=3000
    networks:
      - app-network

  steam-games-api:
    restart: unless-stopped
    container_name: steam-games-api
    image: steam-games-api:0.1
    build: ./steam-games-api
    ports:
      - "8000:8000"
    environment:
      - GAMES_PORT=8000
    networks:
      - app-network

  mongodb:
    restart: unless-stopped
    container_name: mongodb
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
  
  game-vault-frontend:
    restart: unless-stopped
    container_name: game-vault-frontend
    build: ./game-vault-frontend
    ports:
      - "4200:4200"
    depends_on:
      - api-gateway
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    name: app-network
    driver: bridge

